### ISSUE TITLE
API Call failed - Method: post - Action: /login - HTTP Response: 0 (Expected 200)

### ISSUE THREAD

**Issue by kevinwarren** [PENDOnl/Wunderlist2-PHP-Wrapper#8]
Hi,

I keep getting this message.
API Call failed - Method: post - Action: /login - HTTP Response: 0 (Expected 200)

Any ideas?

**Comment by PENDOnl** [comment]
Possibly because there's an error reaching the wunderlist api, is the error still there?

**Comment by pennadl** [comment]
Sometimes happens, usually it's a temporary problem
